### ISSUE TITLE
Reorganize Post Merge

### ISSUE THREAD

**Issue by paltman** [unfoldingWord-dev/translationDatabaseWeb#101]
Bringing in `uwadmin` and thinking through how best to integrate things has led us to question the overall code structure. In thinking about it, I'd like to propose we do the following:

`td.*` should contain code dealing with Language specific things.

`td.resources.*` should contain code dealing with Resources

`td.publishing.*` should contain code dealing with Publishing (mostly what `uwadmin` was)

What this means is moving the following models:

* `td.uw.Network` -> `td.Network`
* `td.uw.Region` -> `td.Region`
* `td.uw.Country` -> `td.Country`
* `td.uw.Language` -> `td.Language`
* `td.uw.EAVBase` -> `td.EAVBase`
* `td.uw.CountryEAV` -> `td.CountryEAV`
* `td.uw.LanguageEAV` -> `td.LanguageEAV`

* `td.uw.Media` -> `td.resources.Media`
* `td.uw.Publisher` -> `td.resources.Publisher`
* `td.uw.Title` -> `td.resources.Title`
* `td.uw.Resource` -> `td.resources.Resource`

* kill `td.uw`

* `td.uwadmin.LangCode` goes away, FK references to it change to `td.Language`
* rename `td.uwadmin` to `td.publishing`

This obviously means porting things like `views.py` and `forms.py` and thinking through url structure, but the basic idea is to organize code around three feature areas: *Language Database*, *Resource Database*, *Publishing Workflow Management*.

**Comment by jag3773** [comment]
Sounds good to me.

**Comment by smcoll** [comment]
Started a `feature/publishing` branch for this ticket.

**Comment by smcoll** [comment]
@paltman why not a `td.languages.*`?  That would allow, for example, the default urlconf to be minimal.
