### ISSUE TITLE
ajax language selector not working in older TD / uW forms

### ISSUE THREAD

**Issue by swilcox** [unfoldingWord-dev/translationDatabaseWeb#105]
Go to uW --> Languages --> select Esperanto (eo) --> click on `eo` --> click on `edit`

You'll notice the gateway language dropdown/lookup doesn't work. 

Same way with Country --> edit... and gateway language selection.

**Comment by paltman** [comment]
Taking a look at this now

**Comment by paltman** [comment]
@swilcox fixed in `feature/publishing` branch
