### ISSUE TITLE
[85]tD.Tracking: Name for the gateway language associated with the translation target language (5)

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#113]
## User Story
As a WA field operations manager, I need a drop-down list to select the gateway language associated with the target language of the translation.

## Definition of Done
The field should be automatically filled based on the user's selection for target language
The submission should not proceed if no gateway language is selected

**Comment by swilcox** [comment]
just FYI, td already has a language to gateway_language relationship setup. So if you were looking at Haitian Kreole (ht), the td uw tables have the info that French (fr) is the gateway language. And, there is a mechanism (form) to edit that via Languages --> Language --> edit

**Comment by vleong2332** [comment]
@swilcox Thanks for letting me know. Will take that into consideration.

**Comment by vleong2332** [comment]
**Question**: Since the relationship already exists, do we still need this field? This info can be pulled for presentation when needed.
