### ISSUE TITLE
Fix GL List

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#139]
The list of GLs needs to be updated based on the latest information at https://unfoldingword.org/gateway/ .  There are officially 44 now.

**Comment by benjore** [comment]
Now we're down to 43.

**Comment by swilcox** [comment]
@jag3773 please check it now. I believe we have it updated. And for future updating... thanks to @smcoll  ... you can now just visit this URL to update (both add and remove from the list) the GL's:

http://td.unfoldingword.org/uw/gateway_language_flag/update/

**Comment by jag3773** [comment]
Awesome, thanks!
