### ISSUE TITLE
Provide Hook for tS to Request to Publish

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#147]
Related to https://github.com/unfoldingWord-dev/Door43/issues/303 .  We need a mechanism whereby translationStudio (in combination with Door43), can initiate a request to publish.

On the tD side, we need some endpoint that tS can hit to fill out the equivalent of the Request to Publish form.

We need to aim to have this ready by Feb 10 so that we can get this feature built into beta6 of tS Desktop (https://github.com/unfoldingWord-dev/ts-desktop/milestones).

**Comment by phillip-hopper** [comment]
Preliminary work on RESTful API in https://github.com/phillip-hopper/translationDatabaseWeb/tree/feature/Issue-147
