### ISSUE TITLE
Publish Request: Add Links

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#167]
We need to add direct links on the publish request form to the License Agreement, the Statement of Faith, and the Translation Guidelines.

**Comment by phillip-hopper** [comment]
@jag3773: Is this what you were envisioning?

![image](https://cloud.githubusercontent.com/assets/5262964/12723372/27078178-c8d7-11e5-84da-202152b97fb1.png)

**Comment by jag3773** [comment]
:+1:
