### ISSUE TITLE
td.tracking: Importing CSV data into tD

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#175]
## User Story

As a manager, I would like to take the CSV data extracted from PDF reports and import them into translationDatabase

## Definition of Done

Add data from CSV file(s) into tD and view that data populated under the corresponding tD Charter/Event

**Comment by vleong2332** [comment]
Mark entered 43 charters. Need date revision once the date range is fixed.
