### ISSUE TITLE
Request to Publish Reject Comment

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#181]
We need to have a small comment form that can accompany a reject message.  The outgoing email should also include a link to a pre-filled form ( see #406 ) that the original requester can go to when the issue has been corrected.

Scenario: user fills out the form and submits it.  We find out that they forgot to attach a license agreement, we reject the request with a message asking them to attach the appropriate files.  They get an email with the comment message and a link.  The link takes them to the same form they originally filled out and they have an option to update it.  They do so and submit.  Request then shows up in the system again and we can approve and publish it.

The reply-to address should be the help desk.

**Comment by phillip-hopper** [comment]
The request to publish feature has been moved to another project.
