### ISSUE TITLE
New field choices added to Output Targets

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#212]
## User Story
As a translation manager I would like new options to choose from in the *Output Target* field to accurately reflect that possible options 

## Definition of Done
Add the following fields to *Output Target*
- [ ] OBS
- [ ] New Testament
- [ ] Complete Bible
- [ ] Custom

**Comment by vleong2332** [comment]
**Question**: How many selections can the user make for this?
