### ISSUE TITLE
New field choices to be added to the Publishing Target

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#213]
## User Story
As a translation manager I would like new options to choose from in the *Publishing Target* field to accurately reflect that possible options 

## Definition of Done
Add the following fields to *Publishing Target*
- [ ] Print on Demand
- [ ] Audio Recording
- [ ] Digital Distribution
- [ ] SD Cards
- [ ] Bible Society

**Comment by vleong2332** [comment]
**Question**: How many selections can the user make for this?
