### ISSUE TITLE
Create ability to originate multiple Charters at one given time

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#214]
## User Story

As a translation manager I would like to have the ability to create multiple charters (from scratch) to save time when faced with a batch of new languages started.

## Use-Case Scenario

- I want to create non-existing project charter for multiple languages.
- Normally, I would need to create the charter one-by-one.
- But that could take a while depending on how many new charters are being created.
- Therefore...
  - I want the ability to create more than one charter in a charter form.
  - I want the option to duplicate information that would be identical across the charters.
  - I want the info that would always be different to not be duplicated.
- As a result, creating multiple project charter for multiple languages can be done in a single form.

~~@Redmayspecial: Would this be the right use-case scenario:~~
~~- I need to record a MAST (or any other) event that involved 3 different languages - Chinese, Japanese, and Korean.~~
~~- Normally, I would need to create 3 separate project charters for each language and would then create the 3 separate, but identical, events with one event associated with one charter.~~
~~- But that would be overly repetitive and  time-consuming.~~
~~- Therefore, I need a way to create an event directly, and at the same time, specifying multiple charters that would "own" this event.~~
~~- I also need an option to copy the same info for all the charters while retaining the ability to make adjustments for each.~~
~~- As a result, with just one form, I'll be able to create multiple project charters that have identical (yet distinct) events. (i.e. Korean charter has an event, Japanese and Chinese charters also have an event that has identical information as the Korean event).~~

## Questions

- Which charter info would always be the same across different charters?
- Which charter info would always be different?

~~- What if a charter already exists for Japanese, but not for Korean and Chinese?~~
~~- How should we address concurrent edit issue? Example: Bob creates a charter for Korean using an "Add Charter" form, while Susan at the same time, is creating a charter for Korean using this new form. Whose creation should be accepted?~~
~~- What if there is slight discrepancy between the two creations?~~

## Possible Solutions

- Use [django-extra-views] (https://github.com/AndrewIngram/django-extra-views) to utilize the custom view
- Also use [django-dynamic-formset] (https://github.com/elo80ka/django-dynamic-formset/blob/master/INSTALL.rst) to add and delete forms

## Definition of Done

![rough wireframe](https://cloud.githubusercontent.com/assets/11600863/10173883/b14f0bb0-66b4-11e5-8a26-f2a1c4105ba8.jpg)

**Comment by Redmayspecial** [comment]
Vicky to create wireframe example for approval

**Comment by Redmayspecial** [comment]
TOP Priority

**Comment by vleong2332** [comment]
@Redmayspecial: Would this be the right use-case scenario:
- I need to record a MAST (or any other) event that involved 3 different languages - Chinese, Japanese, and Korean.
- Normally, I would need to create 3 separate project charters for each language and would then create the same event to each project charters.
- But that would be overly repetitive and  time-consuming.
- Therefore, I need a way to create an event immediately, and at the same time, specifying multiple charters that would "own" this event.
- I also need an option to copy the same info for all the charters while retaining the ability to make adjustments for each.
- As a result, with just one form, I'll be able to create multiple project charters that have identical (yet distinct) events.
-

**Comment by vleong2332** [comment]
# Questions

- Which charter info would always be the same across different charters?
- Which charter info would always be different?
- What if a charter already exists for Japanese, but not for Korean and Chinese?
- How should we address concurrent edit issue? Example: Bob creates a charter for Korean using an "Add Charter" form, while Susan at the same time, is creating a charter for Korean using this new form. Whose creation should be accepted? What if there is slight discrepancy between the two creations?

**Comment by vleong2332** [comment]
# Possible Solutions

- Use Django Form Wizard
  - This will be a separate form, not an augmentation of the normal charter and event form.
  - This will form will have multiple steps to complete
  - The first step: Enter all required and optional event information except for the charter/language
  - The second step:
    - Choose which charters own this event.
    - Give an option to create new charter(s) form with all its information
    - Give an option to duplicate charter info across all the charter forms
  - The third step: Preview prior to submission (?)

**Comment by vleong2332** [comment]
Wireframe and feasible code are made.
