### ISSUE TITLE
Create ability to duplicate a Charter and its Event

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#215]
## User Story

As a translation manager I would like to have the ability to copy a charter and its first event to save time when needing to creating multiple charters at once that share commonality

## Proposed Solutions

Provide a way to associate one event to multiple charters.

## Proposed Tools
- [FormWizard] (https://github.com/django/django-formtools/)
- [jquery.form plugin] (http://malsup.com/jquery/form/)
- [Modal implementation] (http://www.abidibo.net/blog/2014/05/26/how-implement-modal-popup-django-forms-bootstrap/)

## Pictures
1. Only associates/works with **EXISTING**  charters
![new event single events for multiple charter](https://cloud.githubusercontent.com/assets/11132446/10607643/ee033cfc-7708-11e5-8392-3bae3a7fabc3.png)

2. Broken into 2 or 3 steps
![single event to multiple charter step 1](https://cloud.githubusercontent.com/assets/11132446/10614035/1a80aa04-7726-11e5-8f6d-96d86bdbfd93.png)
![new charter modal](https://cloud.githubusercontent.com/assets/11132446/10614034/1a808fc4-7726-11e5-834a-fe1f8f82207e.png)
![single event to multiple charters step 2](https://cloud.githubusercontent.com/assets/11132446/10614033/1a803ab0-7726-11e5-8b0b-6857919277db.png)

**Comment by Redmayspecial** [comment]
Near the Top

**Comment by vleong2332** [comment]
Researched and Wireframed
