### ISSUE TITLE
GL tracker

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#217]
## User Story
As a manager I would like to see the data represented in the GL Tracker to be displayed in the td.unfoldingword.org/uw/languages

## Definition of Done
GL_Tracker (https://docs.google.com/spreadsheets/d/1bcuHUoiDgnzKlgjeW8cvXMek_UIXMjaNgO4QgVN-Tuk/edit#gid=2055750128)

Research DB GL_Tracker compared to the Web-site and see if the information can be served in one place.  Figure out DB data and see if it can be represented on the site.  (Make phone calls and ask questions)

**Comment by Redmayspecial** [comment]
Middle

**Comment by vleong2332** [comment]
This issue will be broken down into several.
