### ISSUE TITLE
Add user accounts

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#218]
## User Story
As a translation manager I need to have an account setup to allow me to enter and edit charter & event information

## Definition of Done
Add the following accounts
- [x] tammy_white@wycliffeassociates.org
- [x] gary_anderson@wycliffeassociates.org
- [x] eric_steggerda@wycliffeassociates.org
- [x] gene_foltz@wycliffeassociates.org
- [x] russ_perry@wycliffeassociates.org
- [x] mark_foster@wycliffeassociates.org
- [x] john_toliver@wycliffeassociates.org
- [x] al_hawthorne@wycliffeassociates.org
- [x] ralph_siebert@wycliffeassociates.org
- [x] marv_lucas@wycliffeassociates.org
- [x] phil_harms@wycliffeassociates.org
- [x] susanne_sell@wycliffeassociates.org
- [x] glenn_oliver@wycliffeassociates.org
- [x] paul_foxworthy@wycliffeassociates.org
- [x] David_Byron@wycliffeassociates.org
- [x] dan_kramer@wycliffeassociates.org
- [x] michael_bush@wycliffeassociates.org
- [x] denese_forkkio@wycliffeassociates.org
- [x] jeewan.rai@wycliffeassociates.org
- [x] steve_ervin@wycliffeassociates.org
- [x] doug_schreiber@wycliffeassociates.org
- [x] dave_wohlers@wycliffeassociates.org
- [x] steve_cammack@wycliffeassociates.org
- [x] ken_keisling@wycliffeassociates.org
- [x] andrew_fitzpatrick@wycliffeassociates.org
- [x] lola_lucas@wycliffeassociates.org
- [x] kwesi_opokudebrah@wycliffeassociates.org
- [x] bob_chambers@wycliffeassociates.org

Passwords should take the form of... Welcomexx321 . Note the W is uppercase and the xx is first initial and last initial.

**Comment by jag3773** [comment]
@vleong2332 Please do *not* use the password provided in this issue.  This is a public issue (hence, not a good idea).

We have (or had) a django app that allows you to invite people by email address, this is the best way to add new users.  Ask @paltman if we still have that running.

**Comment by vleong2332** [comment]
@Redmayspecial : per @jag3773's comment, we should do the invite system for the live website. We can use a separate account for you, Mark, Holly, Paul, and David with default password.

**Comment by Redmayspecial** [comment]
TOP Priority
