### ISSUE TITLE
Importing bulk translator names from spreadsheet

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#230]
## User Story
As a translation manager, I would like the ability to import multiple translator names from an event from a spreadsheet in order to save time entering in information from an Event

## Definition of Done
Import translators as separate line entries from electronic file or spreadsheet

**Comment by Redmayspecial** [comment]
Near the Bottom

**Comment by vleong2332** [comment]
Using (`django-import-export`) [https://django-import-export.readthedocs.org/en/latest/] to import Charter info from admin interface.
