### ISSUE TITLE
Publish Request: Make Review Links Easier to See

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#242]
After the QA runs for a publish request a list of problems are presented but it is not immediately clear to users that each item has a link to the problem.

Let's change the fail message to:

`This resource did not pass the quality check.  Please click each link below and fix the issue mentioned on the Door43 site:`

The entirety of each bullet item mentioned should be a hyperlink and the link should open in a new window (target=_blank).

**Comment by cdaield** [comment]
Closed with PR #291
