### ISSUE TITLE
Add a "License" checkbox for each translator on the charter/event form 

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/translationDatabaseWeb#243]
I noticed on the webcast today that for each translator there is a checkbox for SoF (Statement of Faith) and TG (Translation Guidelines). There is one more requirement that each translator needs to sign and that is the (Creative Commons Attribution-ShareAlike) License. A checkbox third box should be added for "License".

**Comment by benjore** [comment]
Printable forms for SoF, TG, & License are available at https://unfoldingword.org/forms/ . An online form is in the works but not available yet. 

If *each* translator creates a Door43 username or a translationStudio user, then that covers all three (but we need their username from Door43). If multiple people use tS, then they need to sign the printable form.

**Comment by Redmayspecial** [comment]
This issue has now been incorporated into issue #227 and is being closed per Ben's suggestion
