### ISSUE TITLE
Add help descriptor on fields that have checkboxes

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#245]
## User Story
As a translation manager I would like text on the checkbox fields where I am able to choose more than one option in order avoid confusion and make it similar to the cntrl-select descriptors on the page

## Definition of Done
Add the phrase "Check all that apply" to each of the fields that we allow the use to select multiple options

**Comment by vleong2332** [comment]
Added a form notice on new event form, update event form, and multi-charter event form.
