### ISSUE TITLE
td.tracking: Allow Users to add content to selection fields

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#247]
## User Story
As a translation manager I need the ability to add content to the checkbox fields so that I may include new options to accurately reflect what methodologies or tools were used during an Event.

## Definition of Done
Because editors are approved users that have a username and account, they should be allowed to add options to the fields that they use.  However, when this is done, a notification should be sent to the administrator to prompt them to oversee any addition

**Comment by vleong2332** [comment]
User is given a new form if he selects "Other" from one of the list or more. User then  can type in comma-separated values. The program will take that, create new items based on the values, and then replace user's selection with that new item. Admin is emailed at the end of the process.
