### ISSUE TITLE
td.tracking: Adding new language

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#248]
## User Story
As a translation manager I need the ability to add a temporary language code when I cannot find it listed, so that I can start and record work being done in that charter language at the time.

## Definition of Done
How this should be accomplished will need to be defined by Ben Jore and/or Jesse Griffin

**Comment by Redmayspecial** [comment]
Issue raised on 11/21 Standup with Jesse.  This apparently meshes with a corresponding issue in translationStudio.

**Comment by jag3773** [comment]
We are envisioning a page that walks the user through a process.  At a high level, the three fold process is "search, build, request".  The idea is that the user only gets to stage 3 when they are absolutely sure that nothing predefined will work in this case.  Essentially, stage 3 should only be hit when we definitely need to setup a custom private use tag.

* Search for a language code
  * Big and simple search box, similar to the "find" function here (http://r12a.github.io/apps/subtags/)
* Build a language code with known subtags 
  * Build off of an existing language code in tD
  * Use 1 or more known public tags:
    * Script subtag (dropdowns)
    * Region subtag  (dropdowns)
    * Variant subtag  (dropdowns)
    * Extension subtag (maybe not needed)
* Request a private use language code (form)
  * What is the name of your language?
  * What are other names or spellings for your language?
  * Is there a dialect name for your language?
  * What are the names of other dialects in your language?
  * What are the names of similar languages?
  * What countries is your language spoken in?
  * What area is your language spoken in?
  * Is there a language code for your language?
  * What is the name of the script that your language uses?

**Comment by vleong2332** [comment]
@jag3773 @benjore: There is a form that allows user to create a language. I've tested it in my dev env and it directly creates a new language into the db. Do we still want that? Or should we take it out for now?

**Comment by jag3773** [comment]
Only if we can restrict access to who can use it.  At the moment, just letting people create [random] codes will cause a lot of problems in the long run.

**Comment by vleong2332** [comment]
Okay. I won't fix the missing template then at this point. Should we remove the "add" button on the country detail page then?

**Comment by vleong2332** [comment]
Link to create a new language from country detail is taken down.

**Comment by sampeckham** [comment]
Just to clarify, a user would want to request a language because they went to start a project and couldn't find the language they wanted to start a project for?

Which implies:

- A user starts a new project > Taps + button
- User looks at list and can't see their language
- They try the search and get no results.

So, it would seem the current search on the language selection screen should cover your first point. 
If that search returns no results, or even at the bottom of the results it does return, should be a message along the lines of: "Can't find you language? Create/Request it"

That takes them to the option of building on an existing language to create a variant, failing that they go on to the request questionnaire.

So, I think this can be handled in a simple modal dialogues from the search function of create a new project. Does that sound like the right approach?

**Comment by markalolo** [comment]
Per Ops Team leadership meeting today, we are clear to begin work on this issue and it is high priority.

**Comment by DonRitchey** [comment]
Attached is a  revised list of questions (revised by Ralph), to use when user is requesting a language code.  This comment relates to Help Desk Ticket  1848, submitted by Ben.
[Short Language Survey questions.docx](https://github.com/unfoldingWord-dev/translationDatabaseWeb/files/141145/Short.Language.Survey.questions.docx)

**Comment by Redmayspecial** [comment]
Suggested by Jesse to break this issue down into three separate issues

- Search for a language code
- Build a language code with known subtags
- Request a private use language code (form)

**Comment by Redmayspecial** [comment]
WA Action Items

-     Replicate the new language user questionnaire form as built out in TS
-     Work with Joel and Bruce to get the algorithm used to generate project code.

**Comment by Redmayspecial** [comment]
New Language Request Workflow

- It has been suggested that a team member (or members) fill out the new language request in TS to generate a new language code.  
- Where possible the project can be shared to other members of the team via bluetooth, wi-fi, sd, e-mail.
- Where not possible the "special code" can be communicated and entered in manually

**Comment by vleong2332** [comment]
Blocked until I talk to @neutrinog
