### ISSUE TITLE
Create Global Catalog of Resources Available

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#256]
tD needs to present a publicly available JSON endpoint that lists all of the published resources it knows about (OBS, OBS tN, tA, Bible, etc).  The format should mimic https://api.unfoldingword.org/uw/txt/2/catalog.json.  The code that currently generates that catalog is https://github.com/unfoldingWord-dev/tools/blob/master/uw/update_catalog.py#L262.

**Comment by jag3773** [comment]
Note that we need to add a license field to the "status" section, this will contain a short string to indicate what the license is.  Typically this will be "CC BY-SA 4.0", in some cases it may be "Public Domain".

**Comment by cdaield** [comment]
Closed with PR #291
