### ISSUE TITLE
A user must be logged in in order to access to view the language database report information

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#267]
## User Story
As a translation manager I need to have my information about bible translation progress be privileged to users only as there are security risks in certain countries and people groups.

## Definition of Done
Link options should not be available to a user who is not logged in

**Comment by vleong2332** [comment]
- Changed `TemplateView` to `HomeView` for `/tracking/` and inherit from `LoginRequiredMixin`
