### ISSUE TITLE
Clean-up field selectors in the Event Forms

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#268]
## User Story
As a translation manager I need the default in the following fields to be altered to accurately communicate the event that took place,

## Definition of Done
Methodology
- [x] Remove - Door 43 Website
- [x] Remove -translation Studio

Software/App Used
- [x] Alter - Microsoft Word to Word processor
- [x] Remove - translationAcademy

~~Checkbox~~
~~- [ ] Copyright checkbox should be defaulted to checked~~

Publishing Medium
- [x] Alter - Publishing Medium to Distribution Method

**Comment by vleong2332** [comment]
Moved "Copyright checkbox should be defaulted to checked" to its own issue.

**Comment by vleong2332** [comment]
Changed field's label to "Distribution Method" in `models.py`
