### ISSUE TITLE
Add "new start" checkbox to Charter form

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#273]
## User Story
As a translation manager, I need the ability to capture whether or not the language effort is a brand new start in order for others to track "new starts" in the database

## Definition of Done
Dropdown of choices to be provided by Mark Stedman.

**Comment by Redmayspecial** [comment]
This box indicates that this language has never had any language start by any group at all

**Comment by vleong2332** [comment]
Glenn, any priority on this one?

**Comment by vleong2332** [comment]
Resolved by #543
