### ISSUE TITLE
Add metadata to JSON endpoints

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#289]
Related to #256.

Each endpoint needs to include the relevant metadata about the resource.  In particular, the following fields should be included under a 'meta' key:

* lc - the language code of the resource
* mod - unix timestamp of the last time the content was changed
* name - localized name of resource
* slug - the resource slug (e.g. obs, ta, luk, etc.)
* version
* contributors
* checking_level
* source_text
* source_text_version
* publish_date - correlates to when this was approved
* license - typically this will be "CC BY-SA 4.0", in some cases it may be "Public Domain"

**Comment by cdaield** [comment]
Resolved with #315
