### ISSUE TITLE
Update OBS JSON Format

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#290]
Instead of listing the 'img' tag for each frame, which is very redundant and wasting space, it would be better to switch to the following format:

```
"imgs": [
  {
    "size": [ "360px", "2160px" ],
    "src": "https://cdn.unfoldingword.org/obs/jpg/1/{size}/obs-{frame-id}.jpg",
  },
```

This also simplifies our image hosting as we are not supporting custom images per language, which is what the original design was predicated upon.

Each frame entry would only have a "text" and "id" entry at that point.

**Comment by neutrinog** [comment]
looks good. Though to be clear you should break that `{id}` into the chapter and frame id's e.g.

```
"imgs": [
  {
    "size": [ "360px", "2160px" ],
    "src": "https://cdn.unfoldingword.org/obs/jpg/1/{size}/obs-{chapter-id}-{frame-id}.jpg",
  },
```

**Comment by neutrinog** [comment]
Where in the api would this be placed?

**Comment by bknatterud** [comment]
Would we assume that every frame has an image? Maybe there should be a flag to denote if a frame has an image or not? I suppose it could silently fail if there is no image too. But in some situations we may want to lay the view out differently if we know there is no image.

**Comment by jag3773** [comment]
@bknatterud Every frame has an image.  @neutrinog This would show as a sister to "chapters" in the OBS endpoint, e.g. https://api.unfoldingword.org/obs/txt/1/en/obs-en.json.

**Comment by jag3773** [comment]
[Resource Container spec](http://discourse.door43.org/t/resource-containers/53) supersedes this.
