### ISSUE TITLE
Missing information in Global Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#295]
Follow up to #256 .

There are several fields missing in the global catalog at http://td.unfoldingword.org/publishing/catalog.json.  The example is at https://api.unfoldingword.org/uw/txt/2/catalog.json.

* The project information is missing.  There should be a `slug` and `title` entry for each resource.
* The `license` field is missing.  See #256 and #289 for notes.
* The `contributors` field is blank.
* The `date_modified` field is blank

**Comment by cdaield** [comment]
Resolved with #315
