### ISSUE TITLE
tA TOC Not Represented in JSON

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#298]
The TOC for tA is not being modeled in the JSON.  The "chapters" in the JSON should correspond to the highest level of organization:
* Introduction
* Translation Manual
* Checking Manual
* Technology Manual
* Process Manual

The frames should correspond to the actual modules, residing underneath their respective upper level chapter.

In addition, there is probably no reason to have a TOC entry at the top of the JSON, if the JSON models the TOC then it will be present implicitly.

**Comment by richmahn** [comment]
Correct, we shouldn't need the top level TOC, but each manual can have its TOC (as on Door43), but that should be the first frame in its "chapter", not in the Introduction (first chapter)

Each frame should be a module, or Door43 page (presented by a URL) and have its first header's id tag as the frame's id. The ref should be included for each frame (the URL) so we can convert links in other modules to anchors links.

**Comment by jag3773** [comment]
More detail in #301
