### ISSUE TITLE
tA json 'title' and 'ref' in wrong place

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/translationDatabaseWeb#299]
In the structure of the json file, the 'title' and 'ref' should be a properties of the frame rather than the chapter.

**Comment by richmahn** [comment]
A chapter (manual) could have a Title, but also a frame should have a title. The question is, should the HTML in the frame's text also contain the title, the <h# id="..."> tag, etc? That is helpful so I don't have to create the anchors fore each section.

**Comment by cdaield** [comment]
Closed with #302
