### ISSUE TITLE
Production is Not Sending Emails

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#305]
The Publishing events are supposed to be sending emails, but that is not happening from production.  It seems to work from the demo instance though.

**Comment by cdaield** [comment]
I was able to send myself a test email from prod in Django shell just now.

Could this error be related?
https://opbeat.com/door43/td/errors/50/

I invested the email recipient in that error and as it currently appears is fine, along with having been verified at some point.

**Comment by cdaield** [comment]
I believe this was a transient issue, closing for now
