### ISSUE TITLE
td.tracking: Need ability to delete a project charter

### ISSUE THREAD

**Issue by DonRitchey** [unfoldingWord-dev/translationDatabaseWeb#320]
This issue is related to Help Desk Ticket 1511:

Need ability to delete a project charter in translationDatabase when a project charter is linked to the wrong language.  Need ability to delete it and start again.

There is a “Remove” option at the bottom of the form to “Add a new project charter,” but no Remove option at the bottom of the Edit form for the project charter.

**Comment by vleong2332** [comment]
When a project charter is created with the wrong language, user can edit that by going to the language detail and click the "edit" button on the top right side of the screen next to the words "Translation Project". This way, the user won't have to start again, but just edit the wrong language to the correct one.

**Comment by DonRitchey** [comment]
Vicky, Thanks for the information.  I sent your response to Marv Lucas who initiated the Help request.

Don

**Comment by vleong2332** [comment]
This feature is not necessary at this point and is quite dangerous to be made available to all users. For now, if the "edit" functionality doesn't serve the need (in other words, a wrong charter *really* needs to be deleted), please contact me or @Redmayspecial.
