### ISSUE TITLE
GL tracker: Build data model in Django 

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#323]
## User Story
As a manager, I want to see the Global Language tracking data currently located in  Google Sheets to also be represented in translationDatabase.

## Definition of Done
A data model needs to be created in Django based on the model done by Tom in https://wycliffeassociatesinc-my.sharepoint.com/personal/tom_pfadenhauer_wycliffeassociates_org/_layouts/15/WopiFrame.aspx?sourcedoc={561E5F4E-9E11-416F-8CD8-7569ED284517}&file=Ops%20Data%20Model.xlsm&action=default

**Comment by vleong2332** [comment]
Consult with Tom Pfadenhauer about the best way to model this.
