### ISSUE TITLE
Add the ability to search by alternate name

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#376]
## User Story
As a translation manager, I would like to be able to seek a language by it's alternate language name in order to make seeking the language more convenient.

##  Definition of Done

**Comment by Redmayspecial** [comment]
This is dependent on Patrick Altman getting the alternate languages in the JSON file.

**Comment by vleong2332** [comment]
This issue is not dependent on getting the info in language_names.json. These 2 things are separate implementation.

**Comment by vleong2332** [comment]
Implemented in language list. PR will follow.
