### ISSUE TITLE
Docs Associated with Official Resources

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#392]
When people upload documents to a request to publish, those documents need to be tied to that all the way through into an official resource record.  Right now, there is no way to call up the docs from an official resource.

**Comment by phillip-hopper** [comment]
@jag3773 Should this be closed, or maybe assigned to someone else?

**Comment by jag3773** [comment]
Correct, this is now handled in the new [Source Text Request Form](http://ufw.io/pub).
