### ISSUE TITLE
Merriweather font not rendering correctly in Firefox

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/translationDatabaseWeb#393]
The word "Official" is being rendered as "Oiffcial" in Firefox 43.0.1.  Updated to 43.0.4 but it has the same problem.  Tested on Windows 10 and Ubuntu 14.04 with the same results.

![image](https://cloud.githubusercontent.com/assets/5262964/12532705/38f9ceea-c1e8-11e5-989e-11f6e8e01cdb.png)

**Comment by phillip-hopper** [comment]
Another example:

![image](https://cloud.githubusercontent.com/assets/5262964/12532991/226d683c-c1f0-11e5-84ae-e6b0ab2dfc7b.png)

**Comment by vleong2332** [comment]
@phillip-hopper did you fix this? It looks fine on my firefox.
![image](https://cloud.githubusercontent.com/assets/11132446/12719294/2e3e21dc-c8c2-11e5-9f34-20ead93c6f65.png)
![image](https://cloud.githubusercontent.com/assets/11132446/12719312/3d669cc0-c8c2-11e5-8dfa-f0c5446fab50.png)

**Comment by phillip-hopper** [comment]
@vleong2332, no I didn't fix it, but I can't reproduce it now either, so I'll close the issue.
