### ISSUE TITLE
Add ability to submit a request for a new Living Language

### ISSUE THREAD

**Issue by paltman** [unfoldingWord-dev/translationDatabaseWeb#40]
We realize this is the ISO identifier. If we find a language without an identifier, can we (should we) add it to the tD? If so, we need an Add option.

> Is the tD only interested in capturing data about “living” languages? This might be a “duh” question; just clarifying.

**Comment by jag3773** [comment]
Superseded by https://github.com/unfoldingWord-dev/translationDatabaseWeb/issues/248
