### ISSUE TITLE
Add the datasources that contribute to the data represented on the language page

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#400]
## User Story
As a translation manager I would like to be able to see the sources that contribute to the data (linked) listed on the language page so that I don't have to look it up from scratch.

## Definition of Done
Show a source and the information on that language that the source is supplying

Wikipedia - English
"English is a mixture of tutonic and romantic langauges...."

**Comment by vleong2332** [comment]
Per our conversation on Friday, 1/29/2016, when going into the language detail page, we need to make API calls to our resources and display that info in collapsible divs.

**Comment by vleong2332** [comment]
Links to Joshua Project, Ethnologue, People Groups, and Wikipedia are provided in language detail page.
