### ISSUE TITLE
Update partner list based on new information from Paul Foxworthy

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#404]

**Comment by vleong2332** [comment]
Blocked until we got the list from Paul.

**Comment by Redmayspecial** [comment]
Get list from MS

**Comment by Redmayspecial** [comment]
[Copy of FY16 WA Partners List.xlsx](https://github.com/unfoldingWord-dev/translationDatabaseWeb/files/132802/Copy.of.FY16.WA.Partners.List.xlsx)

**Comment by vleong2332** [comment]
Blocked by #427

**Comment by vleong2332** [comment]
@rbnswartz imported it to prod db
