### ISSUE TITLE
Add Available Resources

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#405]
Add all available resources, in the manner shown in the image.

**Comment by benjore** [comment]
![request to publish form](https://cloud.githubusercontent.com/assets/13352518/12647041/4e22797c-c5a1-11e5-8199-c04e852382e5.jpeg)

**Comment by DonRitchey** [comment]
Additional Requests- These requests are related to Help Desk Tickets 1791 and 1792: 

1.  We need the drop-down list for “Official resource type” on the Request to Publish form to include all of the translation tools: ULB, UDB, Bible Notes, translationWords, and Bible Questions. (Ticket 1791)

2.  We need a page of instructions that the user can see before they fill out the RtP form, that tells them what we are looking for in each field. Many people are not filling it out correctly, and that will only get worse as this spreads beyond the situations where WA people are there giving lots of hand holding. (Ticket 1792)

**Comment by jag3773** [comment]
This is now handled in the new [Source Text Request Form](http://ufw.io/pub).
