### ISSUE TITLE
Build UI to all for updating the partner list.

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#427]
## User Story
It would be useful to WA to have a list that would display our approved/active partners, not all partners that exist.  To keep this list current, the user should be allowed to edit the list

Both GL and TD should be sharing the save approved partner list.

**Comment by rbnswartz** [comment]
# Definition of Done
A partner list exists to show existing partners
A partner's details can be displayed
A form exists to allow for the creation and modification of Partners.

**Comment by rbnswartz** [comment]
Merged into master
