### ISSUE TITLE
Add WA_Partner field to the Charter Form

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#442]

**Comment by rbnswartz** [comment]
Hey @markalolo 

Do you think Paul would like partner to be mandatory? My current thinking is no. Also on the delete of a partner do we want it to restrict delete, cascade, null it, or set it to a default value. My current plan is to set it to null but it can be changed if you think it should behave differently. 

This question also needs to be answered for #443

**Comment by vleong2332** [comment]
My vote is `SET_NULL` on delete. We don't want to delete the charter when a partner is deleted.

**Comment by rbnswartz** [comment]
That is what I'm currently implementing but I wanted to get Mark's opinion on it if there was any reason why it should be that way.
