### ISSUE TITLE
Create a workflow diagram to outline language creation process

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#462]
## User Story
We need a shared understanding on how the language questionnaire and language algorithm is designed to work in order to ensure that we have captured use cases.

## Definition of Done
Vicky and Joel to create a shared document.  Vicky will create first draft

**Comment by vleong2332** [comment]
https://docs.google.com/document/d/139IdvveCE2-zjal9smsJAt4GUA1HhavFfZRJ32u5IE4/edit?usp=sharing

**Comment by vleong2332** [comment]
Done.
