### ISSUE TITLE
Default all the current PartnerList to have a Partner Start of 1/1/80

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#484]
## User Story
All of the pre-populated list should have a default Partner Start date of 1/1/80 where our start date is not known in order to indicate that this date has a value but is not known or significant at this time.

**Comment by vleong2332** [comment]
So, on the user side, they would see "1/1/1980" in the table?

**Comment by markalolo** [comment]
Yes, that's fine. We'll just train them that 1/1/80 means "a while ago, where a specific date is not important".

**Comment by vleong2332** [comment]
Done. Set to 1/1/1900.
