### ISSUE TITLE
Display the actual first and last names whenever a username is currently displayed

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#487]
## User Story
As a manager, I would like to see actual user's full names in order to more easily identify individuals rather than their usernames.

## Definition of Done
Anywhere a username or partial name is currently displayed, show the actual first and last name

**Comment by vleong2332** [comment]
Currently, we only fallback to the username if there's no first name or last name on the user. We can:

1. Ask the user to change it themselves
2. Change it for the users through the admin.

**Comment by markalolo** [comment]
Great, maybe we can ask Holly to go thru and add everyone's real name to the existing accounts.

**Comment by vleong2332** [comment]
Fallback set.
