### ISSUE TITLE
Update Regions

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#50]
We need to make the regions that tD is showing match up with the region list on the GL page and that WA uses.  I think that means we add South Asia and change Europe to Eurasia.

Reference https://unfoldingword.org/gateway/ and Help Desk Ticket https://help.door43.org/Ticket/Display.html?id=1479.

**Comment by Redmayspecial** [comment]
## Definition of Done
 - [ ] Change Europe to Eurasia
 - [ ] Add SouthAsia
 - [ ] Backend: Update relationship between country and regions
    (Tom P has relational files)
 - [ ] Send issue to Tom

**Comment by Redmayspecial** [comment]
Dave Byron to provide a list of the Breakdown of the countries and which region above that they belong to.

**Comment by jag3773** [comment]
This should probably be implemented as a new field in the database, rather than trying to modify existing regions.

**Comment by vleong2332** [comment]
Based on our Q1 hackathon, I created the initial mapping between gateway languages and WA region for management purposes. Do you see the need to update the language-to-countries-to-wa_region as well?

**Comment by vleong2332** [comment]
No need to create countries-to-wa_region according to @markalolo
