### ISSUE TITLE
Online Questionnaire: needs a third option to answer text direction

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#503]
## User Story
As a translation manager, I need a different option to answer the question regarding text direction when I am entering in a language with no written word

## Definition of Done
Create a third option of "oral only"

**Comment by vleong2332** [comment]
Changing the direction choice will break things so it's not recommended to do it.

If we still need this distinction, we should add a dedicated field for that (e.g.`Language.is_oral`)
