### ISSUE TITLE
Give weights to documents in GL Tracker

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#528]
## User Story
As a GL Director I wish to have an understanding of percentage done which tracks against word count done vs word count total.  

This will help balance against valuing large book (80,000 words) with smaller books (8,000 words)

The word-counts for most of these portions of text are readily-available within Door43,   (https://door43.org/word-counts)

**Comment by vleong2332** [comment]
Blocked. Need to know how the users would enter the progress: The current drop-down of completion rate *or* the exact word count.

**Comment by markalolo** [comment]
Per the discussion this morning, let's assume that the GL Directors will continue to use the percentage drop-downs.

**Comment by vleong2332** [comment]
Will proceed as mentioned.

This is how weight will affect the current calculation:
- Chinese OBS is marked as 50% complete (Level 2)
- Chinese SoF is marked as 100% complete (Level 3 and published)
- Chinese OBS has 10,000 words
- Chinese SoF has 100 words
- Average completion rate for these 2 documents will be:
  - (50% x 10,000) + (100% x 100) / 10,000 + 100
  - = 5,000 + 100 / 10,000 + 100
  - = 5,100 / 10,100
  - = 0.51 = 51%

**Comment by markalolo** [comment]
Bingo.

**Comment by vleong2332** [comment]
In PR #542
