### ISSUE TITLE
Wireframe the views/screens that will display event counts and "Pivot tables"

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#552]
## User Story
As a translation manager I wish to be able to see a count of the events that have begun by Language, Country, and Region in order to understand the activity happening by each of these categories

**Comment by Redmayspecial** [comment]
![image](https://cloud.githubusercontent.com/assets/11600863/15073446/6fa57e78-1367-11e6-91ff-175f214b1fe5.png)

**Comment by Redmayspecial** [comment]
![image](https://cloud.githubusercontent.com/assets/11600863/15074469/3021d8b8-136d-11e6-8089-03617a63ecb3.png)

**Comment by Redmayspecial** [comment]
![image](https://cloud.githubusercontent.com/assets/11600863/15074477/413b6c7c-136d-11e6-82ed-d314fe1f740b.png)

**Comment by vleong2332** [comment]
Wireframes are up in InvisionApp https://projects.invisionapp.com/d/main#/projects/7313900
