### ISSUE TITLE
Display total Events in a Country

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#556]
## User Story
As a translation manager I would like to see the count of all the event that started in a given month per Country in order to visualize that activity that is going on.

## Definition of Done
Display the Event Dashboard view of all the language events by fiscal year (Oct 1 is Fiscal Start) for that country.

**Comment by vleong2332** [comment]
The discussion come up what determines the true geographical position of an event. Is it the database relation or the value of "location" in the event form?

For example, should an event for Eastern Magar took place in Atlanta be counted for United States/Americas or Nepali/South Asia?

@PurpleGuitar threw the idea that we should show it under both countries and regions. But we need @markalolo, as the PO, to clarify.

**Comment by vleong2332** [comment]
Blocked until clarification received from PO.

**Comment by markalolo** [comment]
Actually we should ask the Ops team. Craig could get clarification on Tuesday.

Typed with some fingers and sent from my gigantic iPad Pro

On May 6, 2016, at 11:15 AM, Vicky Leong <notifications@github.com<mailto:notifications@github.com>> wrote:


The discussion come up what determines the true geographical position of an event. Is it the database relation or the value of "location" in the event form?

For example, should an event for Eastern Magar took place in Atlanta be counted for United States/Americas or Nepali/South Asia?

@PurpleGuitar<https://github.com/PurpleGuitar> threw the idea that we should show it under both countries and regions. But we need @markalolo<https://github.com/markalolo>, as the PO, to clarify.

-
