### ISSUE TITLE
SPIKE: Library for Pivot Table

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#559]
## User Story
Research will need to be done to reveal if there are any library(s) that could assist in the creation and display of a pivot or pivot-like table in which to display to the user

**Comment by vleong2332** [comment]
Per our conversation with @markalolo, we would not need the PivotJS awesome capabilities. Instead, it just a view that count the events and spew out data to the front-end and let the front-end display it in a table format.

**Comment by markalolo** [comment]
I don't want to convey that we'll never need better capabilities but that for now we need to get something simple and functional

Typed with some fingers and sent from my gigantic iPad Pro

On May 6, 2016, at 11:08 AM, Vicky Leong <notifications@github.com<mailto:notifications@github.com>> wrote:


Per our conversation with @markalolo<https://github.com/markalolo>, we would not need the PivotJS awesome capabilities. Instead, it just a view that count the events and spew out data to the front-end and let the front-end display it in a table format.

-
