### ISSUE TITLE
Add the ability to have several fiscal years view-able on the Event Dashboard

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#560]
## User Story
As a translation manager, I would like to have the option to see display the  previous, the present, or the next year worth of data so that I can compare and evaluate?

## Definition of Done

- [x] Mock up the design of how the user would choose these options
- [x] Present the viewer with the Event Dashboard Starting with Oct, 1st of the prior, present, and next year.

**Comment by vleong2332** [comment]
Blocked naturally by #558
