### ISSUE TITLE
Calculate and Display the Events for each language

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#562]
## User Story
As a translation manager, I would like to see the total number of events that have/will be run in support of bible translation for a given language

## Definition of Done
Sum together and display 
- [ ] Events that have completed
- [ ] Events that are currently happening
- [ ] Events that are scheduled in the future

**Comment by vleong2332** [comment]
I don't think this is relevant anymore.
