### ISSUE TITLE
Create a commenting system (Phase 1)

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#568]
## User Story
As a translation manager, I would like to be able to read notes and create notes relevant to the language, country, region, etc.in order to share and store important information with other users of translationDatabase.  I would also like to tag comments for other''s to be able to find them easily.   

## Definition of Done
The comments should utilize hashtags, time-stamps, usernames, and actively allow the user to follow links

**Comment by Redmayspecial** [comment]
From @markalolo 
On the commenting system, I’m thinking about being able to add comments. Comments would be time-stamped and user-stamped. The fun part would be implementing the ability to use hashtags to link the comment to multiple pieces of data. The data I’m thinking about would include:

#country
#region
#language
#project
#event

So when the data was posted into the database, we’d check for hashtags and store those separately, along with the page the comment originated on. Then if you looked at any of the other pages that were hashtagged you’d see the comment there, like this:

Let’s say I’m on a language page like Eastern Bru (http://td.unfoldingword.org/uw/languages/917/). And I enter a comment like:

“This is a dialect of #tdf also spoken in #Laos.”

That comment would show up on Eastern Bru.

And on the Laos Page, you would see a list of comments, including this one that said something like:

“Eastern Bru: This is a dialect of #tdf also spoken in #Laos. – Mark Stedman 4/28/16”

And on the Taileng page it would say something like:

“Eastern Bru (put the actual name here? Hyperlinked?): This is a dialect of Taileng also spoken in #Laos. – Mark Stedman 4/28/16”

**Comment by vleong2332** [comment]
Resolved by #608
