### ISSUE TITLE
Wireframe the commenting system (Phase 1)

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#569]
## User Story
Mock up how the proposed system and features would look for each commenting function

- [ ] Read/Insert comments
- [ ] Using Hashtags
- [ ] Including Mentions

## Definition of Done
Seek approval from Mark Stedman

**Comment by vleong2332** [comment]
For the sake of clarity, let's not use the term "mention" for commenting system. We'll assume that the hashtags are two-way lookups.
