### ISSUE TITLE
Display Fiscal Year information using the actual year not a label

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#579]
## User Story

As a translation manager, I would like the fiscal year to be displayed by actual dates not by "list, last, or next"

## Definition of Done

Also, extend the range if possible.

- Current year - 4, Current year, Current Year +1
- 2012 - 2016, 2016, 2017

**Comment by markalolo** [comment]
To clarify, the choices would be

Current - 4 (2012)
Current - 3 (2013)
Current - 2 (2014)
Current - 1 (2015)
Current (2016)
Current + 1 (2017)

Not a range of 2012-2016



Typed with two thumbs and sent from my iPhone

On May 19, 2016, at 8:10 AM, Glenn Oliver <notifications@github.com<mailto:notifications@github.com>> wrote:

User Story

As a translation manager, I would like the fiscal year to be displayed by actual dates not by "list, last, or next"

Definition of Done

Also, extend the range if possible.

  *   Current year - 4, Current year, Current Year +1
  *   2012 - 2016, 2016, 2017

-

**Comment by vleong2332** [comment]
Resolved by #590
