### ISSUE TITLE
Daemonize Celery

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#58]
The celery process needs daemonized.

**Comment by swilcox** [comment]
@jag3773 What do you mean by this? It is running in production (or should be). Do you need instructions written up for running this locally or is there something that isn't running correctly in production?

**Comment by paltman** [comment]
Perhaps this was for uWadmin

**Comment by jag3773** [comment]
Yep, my bad.
