### ISSUE TITLE
Offline Progress Form

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#59]
We need a form for GL teams to record offline progress.  Such a form should include:

* language name
* resource name (drop down)
* Status (drop down)
* Comment (plain text)

The list of status options needs to be defined.

**Comment by Redmayspecial** [comment]
near the Bottom

**Comment by vleong2332** [comment]
Is this the same as Global Language Tracker issue #217?

**Comment by jag3773** [comment]
Yes, dup of #217
