### ISSUE TITLE
Add ability to programatically identify what information is answered by a custom language code question

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/translationDatabaseWeb#603]
@vleong2332, @Redmayspecial:

This issue relates to the spec at https://github.com/unfoldingWord-dev/ts-requirements/wiki/New-Target-Language-Code.

See API implementation at http://td.unfoldingword.org/api/questionnaire.

The apps need to collect some information from the questionnaire after it is completed in order to correctly utilize the new custom language code. This need can be solved by adding a new field to questions in the api which indicate the type of data provided.

New Field
--
`language_data`

Available Values
--
The values of this new field will correspond to fields found in http://td.unfoldingword.org/exports/langnames.json

* `ln` language name
* `lr` language region
* `ld` language direction

**Comment by PhotoNomad0** [comment]
@neutrinog - we also need a field to identify the question that contains the name of the language.  Currently we are presuming that question one is the name of the language.  Not a good assumption unless we put that in the spec. that the first question is always the name of the language.

**Comment by vleong2332** [comment]
@neutrinog and @PhotoNomad0, for name and direction, tD will know how to get that info from the questions and their answers. For region, tD is going to refer to the country question; and for WA region, Ralph Siebert is the one who's going to fill that in during his review.

As far as tD is concerned, those info will be filled out once the request is submitted. Are you needing those info pre-submission?

**Comment by neutrinog** [comment]
@vleong2332 we need language name and direction pre-submission.

**Comment by vleong2332** [comment]
So something like this? http://www.jsoneditoronline.org/?id=27ff9243200aaee0552729c5ee05df5f

**Comment by neutrinog** [comment]
that wasn't exactly what I was thinking, but I like it better! :)

**Comment by PhotoNomad0** [comment]
Yes, that will be great!

**Comment by vleong2332** [comment]
Resolved by #607
