### ISSUE TITLE
Merge "Is Gateway" Field

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#64]
In the language lists the "Is Gateway" column should be merge into the Gateway Language column to conserve space.

**Comment by vleong2332** [comment]
After thinking about it, the column on the language list could be used to "filter-by-sort" languages that are gateway languages. So it could be useful to keep it on a separate column. To conserve space, maybe we can just rename the header to "Gateway" instead of "Gateway Flag"?

**Comment by jag3773** [comment]
Yes, let's call that good.

**Comment by Redmayspecial** [comment]
Jesse G. said to "call this issue done"
