### ISSUE TITLE
Publish tA vol1 to uW Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#68]
_From @jag3773 on July 29, 2015 20:5_

Related to #41, unfoldingWord-dev/tools#113, and unfoldingWord-dev/tools#112.

We need to write a publishing routing to get tA vol1 into the catalog.

Each entry should have an ID that is the "slug" field in the source YAML matter.  It's possible that we'll need to prefix the slug with vol1-slug and/or vol2-slug in order to avoid collisions (please first check to see if there are any existing collisions before implementing that though).  This comment replaces #72 .

_Copied from original issue: unfoldingWord-dev/uwadmin#49_

**Comment by jag3773** [comment]
@benjore @richmahn @phillip-hopper We need a way to determine all of the tA pages and their relationships so that tD can suck in that information and generate a JSON representation of it.

What are your thoughts on that?  I *think* that we want to be pulling from the Door43 pages, not the Etherpad pages, is that correct @benjore ?

**Comment by richmahn** [comment]
@jag3773 Would this JSON have all the content of each page? How should relationships be represented? I suggest we make a plugin that gathers all that information of a given namespace. I was working on such a plugin when working on the tA PDF export

**Comment by jag3773** [comment]
Note that relevant code that should be consulted is at https://github.com/unfoldingWord-dev/tools/blob/master/ta/etherpad_to_dokuwiki.py and https://github.com/unfoldingWord-dev/tools/pull/131

**Comment by jag3773** [comment]
The TOC for tA is at https://door43.org/en/ta/vol1/toc.  Pragmatically, each link on that page can be imported as it's own module/page.  We'll want to make store the TOC itself as well, so that we can present the items appropriately.

**Comment by cdaield** [comment]
Changes can be found in #260

**Comment by cdaield** [comment]
Pull request #260 has been accepted and merged to develop
