### ISSUE TITLE
PNB - Western Panjabi [sic] should be Right-to-Left

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/translationDatabaseWeb#710]
Western Punjabi is a right-to-left language, but tD lists it as left-to-right. As a result, all projects created in tS mis-display the text.

Please correct the database so that tS can properly use Western Punjabi.

**Comment by jag3773** [comment]
@mondele I've made the change, it may take a few minutes for the langnames.json endpoint to get updated, but after that a language list update in tS should correct the issue.
