### ISSUE TITLE
Name of Western Panjabi should be پنجابی

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/translationDatabaseWeb#711]
Currently, the updated name for `pnb` is "لہندا پنجابی". Native speakers say that this is a meaningless expression, and Google translate renders it as "Hindi Punjabi". It should be changed to "پنجابی", which just means Punjabi, and the arabic script will inform the reader that it is the Western Punjabi spoken in Pakistan.

**Comment by jag3773** [comment]
I made the change earlier today @mondele , thank you!
