### ISSUE TITLE
Audio: Publishing to API

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#79]
_From @jag3773 on July 16, 2015 16:6_

Solidify JSON format for audio and then write the routines to publish the files and generate the catalog correctly.  Rough draft at https://docs.google.com/document/d/19NY23hnZCuhvILheQDt73Rh9sa6rgeTW7hkbzeg1VDA/ .

_Copied from original issue: unfoldingWord-dev/uwadmin#40_

**Comment by jag3773** [comment]
We have decided that we will be providing 2 formats by default in the catalog:
→MP3 128kbps
→MP3 48kbps

Apps, sites, etc. that consume this should represent this as a low / high quality option.

**Comment by jag3773** [comment]
@richmahn is this done now?

**Comment by richmahn** [comment]
@jag3773 There has been no code written to generate the JSON file. I had done it by hand by searching and replacing each entry in the JSON file and adding the same lines for audio and video. I can work on this next week if we have definitely confirmed the whole format of this part of the JSON.

**Comment by jag3773** [comment]
Initial code written in https://github.com/unfoldingWord-dev/tools/commit/12a26b2d2c33b8a70550af0c6113c6dfaf318db5 and https://github.com/unfoldingWord-dev/tools/commit/51a1b11217b60c4c6981af4391550191d8510f47 .

Much of that will need rewritten when we start managing this in tD.
