### ISSUE TITLE
Notification of decommissioning

### ISSUE THREAD

**Issue by yakob-aleksandrovich** [unfoldingWord-dev/translationDatabaseWeb#790]
@jacobwegner we are in the process of decommissioning the translationDatabase website. As part of that process, we want to place a notification on the website. Can you please assist us in doing so?

**Comment by jacobwegner** [comment]
@yakob-aleksandrovich:  Sure.  What would you like the message to say?

<img width="1031" alt="image" src="https://github.com/unfoldingWord-dev/translationDatabaseWeb/assets/629062/119ca9ee-79d3-4fc8-9e41-0e0560690ebb">

**Comment by yakob-aleksandrovich** [comment]
This is the text that we would like to see

Dear users,

We regret to inform you that translationDatabase will be decommissioned soon. After careful consideration, we have decided to discontinue this website and focus our efforts on other projects.

Effective from August 31st, the main website will no longer be available, and you will be forwarded to [[openlanguages.io](http://openlanguages.io/)](http://openlanguages.io) instead. This website is currently under construction. The basic language name and code information found at [[td.unfoldingword.org/exports/langnames.json](http://td.unfoldingword.org/exports/langnames.json)](http://td.unfoldingword.org/exports/langnames.json) will remain at that location for compatibility. You may continue to point applications at that endpoint for basic language information.

**Comment by jacobwegner** [comment]
I’ll get this onto the demo instance in the next day or so; if it looks ok there, we can promote to the production instance.On Jun 5, 2023, at 1:11 PM, Якоб Александрович ***@***.***> wrote:﻿
This is the text that we would like to see
Dear users,
We regret to inform you that translationDatabase will be decommissioned soon. After careful consideration, we have decided to discontinue this website and focus our efforts on other projects.
Effective from August 31st, the main website will no longer be available, and you will be forwarded to [openlanguages.io](http://openlanguages.io) instead. This website is currently under construction. The basic language name and code information found at [td.unfoldingword.org/exports/langnames.json](http://td.unfoldingword.org/exports/langnames.json) will remain at that location for compatibility. You may continue to point applications at that endpoint for basic language information.

**Comment by jacobwegner** [comment]
@yakob-aleksandrovich: The demo instance has been updated:

https://translation-database-demo.herokuapp.com/

<img width="756" alt="image" src="https://github.com/unfoldingWord-dev/translationDatabaseWeb/assets/629062/7e1886a5-7ef9-4257-8d38-f7507e5a67c6">

If that looks ok, please merge https://github.com/unfoldingWord-dev/translationDatabaseWeb/pull/791 and then I will make sure it gets deployed.

Thanks!

**Comment by yakob-aleksandrovich** [comment]
Merged it. Please deploy.

**Comment by jacobwegner** [comment]
@yakob-aleksandrovich: Done!

https://td.unfoldingword.org/

<img width="756" alt="image" src="https://github.com/unfoldingWord-dev/translationDatabaseWeb/assets/629062/937124e2-cd04-43e2-8935-efca057e8987">
