### ISSUE TITLE
OBS Publishing

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationDatabaseWeb#90]
_From @jag3773 on June 8, 2015 18:17_

Web interface should trigger the publishing process.

_Copied from original issue: unfoldingWord-dev/uwadmin#22_

**Comment by jag3773** [comment]
The overall procedure is diagrammed here: https://door43.org/en/dev/uwadmin.

**Comment by jag3773** [comment]
A detailed diagram is at https://door43.org/en/dev/publishing_workflow_detailed.

**Comment by jag3773** [comment]
Perhaps the initial form should be multi-page, that way we could provide relevant information throughout the process.  If they just enter the language, project, and desired checking level on the first page then we could give them helpful links and information on the second page related to those details (e.g. like what all is required for a level 1, 2, or 3 check and the immediate technical feedback info).  This may be a longer term goal, but I wanted to note it here for future reference.

**Comment by jag3773** [comment]
@phillip-hopper This is something of a meta-ticket, it may be redundant at this point but thought I'd assign it to you so you are aware of it.

**Comment by phillip-hopper** [comment]
This task has been moved to another project.
